name: open_control
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio:
  sliding_up_panel: ^2.0.0+1
  dropdown_button2:
  grouped_list: ^5.1.2
  cupertino_icons: ^1.0.2
  zego_uikit_prebuilt_video_conference: ^2.2.8
  speech_to_text: ^6.1.1
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  mask_text_input_formatter: ^2.4.0
  intl: ^0.17.0
  mobx: 
  flutter_mobx:
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  json_serializable: ^6.1.4
  mobx_codegen:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PTSerif
      fonts:
        - asset: assets/fonts/PTSerif-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
