// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCABuVR-s6OQ3jCXeDvzvC6QPB1FlihCjg',
    appId: '1:352395501319:web:c04dfddd19e84d8dedafa2',
    messagingSenderId: '352395501319',
    projectId: 'open-control-hack',
    authDomain: 'open-control-hack.firebaseapp.com',
    storageBucket: 'open-control-hack.appspot.com',
    measurementId: 'G-3XJVYX12JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSanjrCPK67SNlE6CB3nFkJMIHLEbKmM4',
    appId: '1:352395501319:android:e4ad4d098f25556aedafa2',
    messagingSenderId: '352395501319',
    projectId: 'open-control-hack',
    storageBucket: 'open-control-hack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPUUtR7fV1cmXkuWKLqy42NnEPEpUcbR0',
    appId: '1:352395501319:ios:79c7669ded28cd4bedafa2',
    messagingSenderId: '352395501319',
    projectId: 'open-control-hack',
    storageBucket: 'open-control-hack.appspot.com',
    iosBundleId: 'com.example.openControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPUUtR7fV1cmXkuWKLqy42NnEPEpUcbR0',
    appId: '1:352395501319:ios:79c7669ded28cd4bedafa2',
    messagingSenderId: '352395501319',
    projectId: 'open-control-hack',
    storageBucket: 'open-control-hack.appspot.com',
    iosBundleId: 'com.example.openControl',
  );
}
